### ISSUE TITLE
Fritzing - Desenhar ligação eletrônica arduino|controle

### ISSUE THREAD

**Issue by HPparanhos** [emersonmoretto/CITI-OpenLung#11]
Pessoal, me mandem umas fotos de referência da ligação de vocês no whatsapp.

Amanhã vou sentar para realizar os desenhos das nossas ligações e aproveito para fazer a versão de vocês. Precisamos documentar toda parte de ligação do arduino para que pessoal possa replicar os testes em outros lugares.

Vamo que vamo!

**Comment by atodobom** [comment]
Olá paranhos. Como pretende fazer a interface?
Estou pensando em uma IHM com tablet, conectado via Bluetooth.
Criei uma Issue em separado com detalhes para não poluir essa aqui.

**Comment by HPparanhos** [comment]
https://github.com/HPparanhos/CITI-OpenLung/tree/master/Images/Video_test

Parte de controle já foi feita usando o arduino mesmo, ele fará o controle de telemetria e o CLP fará o controle de motor e válvulas. Os dois terão comunicação entre si.

Estamos adaptando novos sensores e brincando um pouco com Blender, em breve teremos alguns vídeos para publicação. 

Abraço!

**Comment by HPparanhos** [comment]
Sobre um produto com Wi-fi ou bluetooth, ele deve ser submetido a duas provas de inmetro especifico, para um produto de mercado no caso. Cada teste de validação gera em torno de 20K Reais, e pode ser facilmente reprovado. 

Não sei ao certo como seria neste caso junto a ANVISA.

 Mas creio que o mais simples é adequado para situação que estamos prevendo.

**Comment by atodobom** [comment]
O usuário, médico ou enfermeiro, vai precisar interagir com o CLP? Isso seria complicado para certificar.
Podemos fazer a IHM simplificada e através dela realizar os ajustes necessários no CLP?
Por exemplo, o perfil do paciente, alterando o volume de ar fornecido por respiração e a frequência respiratória.

**Comment by HPparanhos** [comment]
No vídeo que mandei a cima tem a interface. Toda via potenciômetro e tela no arduino. CLP apenas controla os motores.

**Comment by AlvaroAguiar** [comment]
> https://github.com/HPparanhos/CITI-OpenLung/tree/master/Images/Video_test
> 
> Parte de controle já foi feita usando o arduino mesmo, ele fará o controle de telemetria e o CLP fará o controle de motor e válvulas. Os dois terão comunicação entre si.
> 
> Estamos adaptando novos sensores e brincando um pouco com Blender, em breve teremos alguns vídeos para publicação.
> 
> Abraço!

O link não leva a uma página válida.

**Comment by breno-helf** [comment]
Oi @AlvaroAguiar acho que tiraram o link para o Vídeo test, acredito que foi por questões regulatórias. @OttoHeringer pode confirmar?
