### ISSUE TITLE
How to contribute to research from Brazil

### ISSUE THREAD

**Issue by andrevtg** [emersonmoretto/CITI-OpenLung#2]
Qual impressora 3D é viável para experimentar? Pode enumerar alguns modelos disponíveis por aqui?

What apropriate 3D printer is available? Can you recomend any models in Brazil?

**Comment by OttoHeringer** [comment]
Oi André. Obrigado por se engajar tão cedo no projeto!
Desculpe a demora em responder. O projeto começou mais rápido do que nossa capacidade de organizar as coisas aqui pelo GitHub também.

Nesse meio tempo demos uma organizada por aqui, apesar de ainda estar faltando algumas coisas.
Acredito que sua pergunta seja respondida dando uma olhada no recente documento [princípios de design](https://github.com/Inspire-Poli-USP/Inspire-OpenLung/blob/master/DESIGN_PRINCIPLES.md) e dando uma olhada também na nossa [abordagem de trabalho](https://github.com/Inspire-Poli-USP/Inspire-OpenLung#nossa-abordagem-de-trabalho-e-princ%C3%ADpios-de-design).

Por enquanto, o limitante que as pessoas estão tendo não é mais construir o protótipo, mas saber como e onde testá-lo usando equipamentos que simulem um pulmão e meçam com precisão a pressão e/ou vazão durante os ciclos de respiração.

Em breve colocarei mais informações sobre essas questões aqui no repositório e as linkarei aqui.
