### ISSUE TITLE
Botão de Contribuição

### ISSUE THREAD

**Issue by OttoHeringer** [emersonmoretto/CITI-OpenLung#24]
And the sponsor button.

_Originally posted by @KChernenko in https://github.com/Inspire-Poli-USP/Inspire-OpenLung/issues/1#issuecomment-602097238_

**Comment by breno-helf** [comment]
Oi @OttoHeringer ! Dentro do PR #9 tem a inclusão de um botão de sponsor. Vocês tem um link de Vaquinha ou algo do gênero? Posso fazer isso :D.

**Comment by breno-helf** [comment]
Resolvido pelo PR #53
