### ISSUE TITLE
Criar um sistema de Integração contínua

### ISSUE THREAD

**Issue by breno-helf** [emersonmoretto/CITI-OpenLung#29]
Acredito que isso seja interessante, mesmo o projeto sendo focado em hardware podemos configurar um sistema de integração contínua para assegurar certas qualidades nas contribuições. Poderíamos configurar um sistema como https://travis-ci.com/ para "testar" contribuições como:
 - Verificar se dados novos são submetidos no formato correto
 - Verificar se mudanças de software passam testes existentes
 - Verificar se mudanças no relatório não apagam coisas que não deveriam ser apagadas

Isso seria um passo em assegurar a qualidade de novas contribuições.

**Comment by TiagoDanin** [comment]
@OttoHeringer Estou trabalhando nisto!

**Comment by breno-helf** [comment]
Obrigado @TiagoDanin , já vou dar uma olhada.
