### ISSUE TITLE
Curva de respiração padrão ou curva adaptável à realidade de cada paciente?

### ISSUE THREAD

**Issue by AlvaroAguiar** [emersonmoretto/CITI-OpenLung#45]
Acredito que muitos desses respiradores talvez usem sistemas on-off como modelos de controle. Para se ter uma ideia. Umas das pesquisas usadas em um incubadora neonatal profissional usada na universidade que fiz mestrado e doutorado usava on-off no controle.

_Originally posted by @marcusvscosta in https://github.com/Inspire-Poli-USP/Inspire-OpenLung/issues/33#issuecomment-610977832_

O projeto prevê tipos diferentes de usuários (pacientes)? Acredito que a curva de respiração de um bebê seja diferente da de um adulto ou de um idoso com asma, por exemplo (relativamente à pressão e tempo). Sugiro diferentes versões do programa: A. bebês; B.Crianças; C. Adultos; D. Idosos.... etc. que seriam setadas pelo técnico responsável (intensivista)/ médico de plantão no CTI.

**Comment by OttoHeringer** [comment]
Oi @AlvaroAguiar , eu atualizei uma documentação para esclarecer melhor sobre esse ponto que você levantou nesse Issue:
https://github.com/Inspire-Poli-USP/Inspire-OpenLung/wiki/Entenda-o-Problema#vari%C3%A1veis-de-cada-paciente
