### ISSUE TITLE
INSPIRE

### ISSUE THREAD

**Issue by RodrigoCaetano1** [emersonmoretto/CITI-OpenLung#8]

**Comment by m-rodrigues-souza** [comment]
Trabalho na PPA, fabricante de automatizadores de portas e portões, já fizemos as partes mecânicas do projeto de vocês, gostaríamos de fazer um protótipo completo, o firmware que está no github é o mais atualizado? Também temos interesse em ajudar na produção em massa, como devemos proceder?

Obrigado!

**Comment by emersonmoretto** [comment]
Opa!!

Me passa seu contato (whatsapp/telefone) por gentileza?


*Emerson Moretto*
emerson@moretto.eng.br
11 99484-0571

**Comment by m-rodrigues-souza** [comment]
*Matheus Souza*
math.souza@gmail.com
